services:

  mariadb:
    container_name: booklore-mariadb
    image: mariadb:12
    networks:
      - booklore
    volumes:
      - ./docker/mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: booklore

      MYSQL_DATABASE: booklore
      MYSQL_USER: booklore
      MYSQL_PASSWORD: booklore
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost", "-uroot", "-pbooklore" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: booklore-backend
    image: amazoncorretto:25-alpine-jdk
    networks:
      - booklore
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    volumes:
      # Source code
      - ./booklore-api:/booklore-api

      - ./docker/backend-data:/app/data
      - ./docker/books:/books
    environment:
      - DATABASE_URL=jdbc:mariadb://mariadb:3306/booklore
      - DATABASE_USERNAME=booklore
      - DATABASE_PASSWORD=booklore
    stdin_open: true
    tty: true
    command: sh -c "cd /booklore-api && ./gradlew bootRun"
    depends_on:
      - mariadb
    restart: unless-stopped

  ui:
    container_name: booklore-frontend
    image: marcaureln/volta:2.0.1
    networks:
      - booklore
    ports:
      - "${FRONTEND_PORT:-4200}:4200"
    volumes:
      # Source code
      - ./booklore-ui:/angular-app
    environment:
      - VOLTA_FEATURE_PNPM=1
      - NODE_ENV=development
    stdin_open: true
    tty: true
    command: sh -c "cd /angular-app && pnpm install && pnpm ng serve --host 0.0.0.0"
    restart: unless-stopped

networks:
  booklore:
    name: booklore