

app:
  path-book: '/Users/aditya.chandel/my-library-temp/books'
  path-config: '/Users/aditya.chandel/my-library-temp/config/local'

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    async:
      request-timeout: 600000
  application:
    name: booklore-api
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:tcp://localhost:8040/~/my-library-temp/config/local/db/booklore'
    username: sa
    password: password
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          order_inserts: true
          order_updates: true
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.apache.fontbox: ERROR
    org.apache.pdfbox: ERROR

server:
  port: 7050