app:
  path-book: '/app/books'
  path-config: '/app/config'

security:
  jwt:
    secret: G6u4m3g7M/b93k7m9a1h1Kw4l3D+5WqXldpl4nTjl4s=
    expiration: 36000000  # 10 hours in milliseconds
    refreshExpiration: 604800000  # 7 days in milliseconds

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    async:
      request-timeout: 600000
  application:
    name: booklore-api
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:/app/config/db/booklore'
    username: sa
    password: password
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          order_inserts: true
          order_updates: true
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.apache.fontbox: ERROR
    org.apache.pdfbox: ERROR